### ISSUE TITLE
How do I call the modal in the blade file?

### ISSUE THREAD

**Issue by fronbow** [LarawireGarage/larawire-modals#3]
Hi

Thanks for creating this component, as the title suggests, How do I call my modal from a button in a blade file?
Also, how do I pass arguments in to the component too?

(I'm hoping your component will allow me to easily call dynamic modals as I wasn't having much luck with the most popular component!!)

Cheers

**Comment by LarawireGarage** [comment]
@fronbow,  I am very sorry for the late reply 🙏. I am little bit busy last few weeks.

For your question, This component is a regular livewire component. So you can called or fire events like normal livewire component.

If you needs to show modal from blade file, 

> You can use `$dispatchTo()` js function in livewire to dispatch "show" event in Modal Component.

```blade
<button wire:click="$dispatchTo('your-modal-component', 'show', { id: {{ $post->id }} })">
    Show Modal
</button>
```

To catch the parameters you need to define **beforeShow()** function (hook).  
```php
// YourModalComponent.php

class YourModalComponent extends ModalComponent {
  public $post_id;

  public function beforeShow($id) {
      $this->post_id = $id; // something like this
  }
}
```

> Hope this reply answer your question...!!! 😊
