### ISSUE TITLE
[BUG] artisan command isn't creating the Class file :(

### ISSUE THREAD

**Issue by fronbow** [LarawireGarage/larawire-modals#6]
Hiya

Thanks for answering my previous query :)

I've just updated, and now I can't get `php artisan make:modal MyModal` to create the class file, it's creating the view files okay, just not the component class file.
Luckily I've got one I can c+p from before I updated, but it would be nice for your lib to work again :)

Cheers matey

**Comment by fronbow** [comment]
Further to this I've worked out that the command is creating the file but on linux it's enclosed in single quotation marks, so in my app directory I had a file called `'Livewire\Modals\AddClientModal.php'` which obviously wasn't in the `Livewire\Modals` directory as the single quotes were a part of the filename!

**Comment by LarawireGarage** [comment]
> Further to this I've worked out that the command is creating the file but on linux it's enclosed in single quotation marks, so in my app directory I had a file called `'Livewire\Modals\AddClientModal.php'` which obviously wasn't in the `Livewire\Modals` directory as the single quotes were a part of the filename!

Oh My bad, I working on windows platform. So I didn't test with Linux platform. I checked by installing fresh Laravel project and install the larawire-modal package on windows. It worked fine. I will look into it for Linux platform. Thanks for noticing that and create this issue.... ❤️

**Comment by LarawireGarage** [comment]
I added a patch for issue of creating modal class file. 

Update to v0.1.3.
```
composer require larawire-garage/larawire-modals:v0.1.3
```

Check it out and let me know if you still have any issue creating model class and blade files in Linux platform.
Sorry for take some time for patch this... 🙏
